### ISSUE TITLE
Add missing helpers

### ISSUE THREAD

**Issue by ero-qt** [Voxelse/LiveSplit.VoxSplitter#1]
Hey!

This repo is currently missing the entirety of the Unreal helpers used in [LiveSplit.SuperMagbot](https://github.com/Voxelse/LiveSplit.SuperMagbot). It would be great help if those could be added as well.

**Comment by Voxelse** [comment]
I initially wanted to rework/improve the helper but since I stopped doing speedrunning related things I never pushed it.
But if it can help, here it is. [1182ca1](https://github.com/Voxelse/Voxif/commit/1182ca1b2b3f4416e96564114aa577e5c9ae732e)
